<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <title>Chatbot Konseling Stress + Grafik Emosi</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> <!-- Load Chart.js -->
  <style>
    body {
      font-family: Arial, sans-serif;
      background: #f0f4f8;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
    }
    .chat-container {
      background: white;
      padding: 20px;
      border-radius: 10px;
      width: 400px;
      height: 600px;
      display: flex;
      flex-direction: column;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
      overflow: hidden;
    }
    .messages {
      flex: 1;
      overflow-y: auto;
      margin-bottom: 10px;
    }
    .message {
      background: #e0e0e0;
      padding: 8px 12px;
      margin: 5px 0;
      border-radius: 5px;
      max-width: 80%;
    }
    .user {
      background: #d1e7dd;
      align-self: flex-end;
    }
    input, button {
      padding: 10px;
      font-size: 16px;
      margin-top: 5px;
    }
    #summary {
      display: none;
      padding: 20px;
      background: #ffffff;
      border: 2px solid #4CAF50;
      border-radius: 10px;
      margin-top: 10px;
    }
    canvas {
      margin-top: 20px;
      background: #ffffff;
      border-radius: 10px;
      padding: 10px;
    }
  </style>
</head>
<body>

<div class="chat-container">
  <div class="messages" id="chatBox">
    <div class="message">Halo! Aku adalah konselor virtualmu. Ceritakan perasaanmu hari ini!</div>
  </div>
  <input type="text" id="userInput" placeholder="Ketik di sini...">
  <button onclick="sendMessage()">Kirim</button>
  <div id="summary">
    <h3>Ringkasan Emosi</h3>
    <canvas id="emotionChart"></canvas>
  </div>
</div>

<script>
  let emotionLog = JSON.parse(localStorage.getItem('emotionLog')) || [];

  function sendMessage() {
    const input = document.getElementById('userInput');
    const chatBox = document.getElementById('chatBox');
    const userText = input.value.trim();

    if (userText !== '') {
      const userMsg = document.createElement('div');
      userMsg.className = 'message user';
      userMsg.innerText = userText;
      chatBox.appendChild(userMsg);

      setTimeout(() => {
        const botResponse = getBotResponse(userText);
        const botMsg = document.createElement('div');
        botMsg.className = 'message';
        botMsg.innerText = botResponse.message;
        chatBox.appendChild(botMsg);

        if (botResponse.emotion) {
          emotionLog.push(botResponse.emotion);
          localStorage.setItem('emotionLog', JSON.stringify(emotionLog));
        }

        if (emotionLog.length >= 7) {
          showSummary();
        }

        chatBox.scrollTop = chatBox.scrollHeight;
      }, 500);

      input.value = '';
      chatBox.scrollTop = chatBox.scrollHeight;
    }
  }

  function getBotResponse(input) {
    input = input.toLowerCase();

    if (input.includes('stres') || input.includes('stress')) {
      return { message: "Aku mengerti kamu sedang merasa stres. Mau coba latihan pernapasan bersama?", emotion: "stres" };
    } else if (input.includes('cemas') || input.includes('takut') || input.includes('khawatir')) {
      return { message: "Cemas itu wajar. Ayo kita tarik napas perlahan bersama.", emotion: "cemas" };
    } else if (input.includes('marah') || input.includes('kesal')) {
      return { message: "Aku memahami kemarahanmu. Mau berbagi lebih banyak?", emotion: "marah" };
    } else if (input.includes('sedih') || input.includes('kecewa') || input.includes('down')) {
      return { message: "Sedih adalah bagian dari perjalanan hidup. Aku mendengarkanmu.", emotion: "sedih" };
    } else if (input.includes('bahagia') || input.includes('senang')) {
      return { message: "Senang mendengar kabar bahagia darimu! Tetap semangat!", emotion: "bahagia" };
    } else {
      return { message: "Terima kasih sudah berbagi. Ceritakan lebih banyak jika mau!", emotion: null };
    }
  }

  function showSummary() {
    const summaryDiv = document.getElementById('summary');
    summaryDiv.style.display = "block";

    const count = {};

    emotionLog.forEach(emotion => {
      count[emotion] = (count[emotion] || 0) + 1;
    });

    // Grafik Emosi
    const ctx = document.getElementById('emotionChart').getContext('2d');
    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: Object.keys(count),
        datasets: [{
          label: 'Jumlah Emosi',
          data: Object.values(count),
          backgroundColor: ['#FF6384', '#36A2EB', '#FFCE56', '#4BC0C0', '#9966FF'],
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true,
            ticks: {
              precision:0
            }
          }
        }
      }
    });
  }

  // Jika sudah pernah 7+ emosi, tampilkan ringkasan saat reload
  if (emotionLog.length >= 7) {
    showSummary();
  }
</script>

</body>
</html>
# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
